### ISSUE TITLE
CDD API for AI

### ISSUE THREAD

**Issue by R41N9** [cEDH-Decklist-Database/cEDH-Decklist-Database#4]
Hello AverageDragon,

I am working on an AI project in python. I would like to use your database to teach my machine what cards are better than others, what cards synergize well with others, and which cards are good with which commanders. I am in the beginning stages of the project, and if you think there's a better option, I'm all ears. However, your database seems to be the A1 choice for cEDH. Please let me know what you think, I'd be happy to have the code hosted on your site when it's ready.

Best regards,
R41N9

**Comment by cococov** [comment]
You will need to scrap or use the private moxfield API to get the cards and deck information. I already did it [here](https://github.com/cococov/cedh-analytics/blob/main/pages/api/data.ts), but the output is molded for my purposes.
